require "../spec_helper"

describe Lavinmq::Producer do
  pending "buffers messages during disconnect (requires server)"
  pending "sends buffered messages on reconnection (requires server)"
  pending "drops oldest message when buffer exceeds 10k (requires server)"
  pending "can be configured with block policy (requires server)"
  pending "can be configured with raise policy (requires server)"
  pending "can be configured with drop oldest policy (requires server)"
  pending "blocks when buffer is full (requires server)"
  pending "raises when buffer is full (requires server)"
  pending "can be closed (requires server)"
  pending "calls on_drop callback when buffer is full (requires server)"
  pending "has on_confirm callback for successful publishes (requires server)"
  pending "has on_nack callback for nacked messages (requires server)"
  pending "has on_error callback for failed publishes (requires server)"
  pending "exposes buffer size and capacity (requires server)"
  pending "clears cached channel when it's closed (requires server)"
  pending "recreates channel when closed channel is detected (requires server)"
  pending "drops messages after max flush retries (requires server)"
end
